version: '3.8'
services:
  web:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - database:/data/db
    ports:
      - '27017:27017'
